### ISSUE TITLE
Testing components that import .env variables do not work

### ISSUE THREAD

**Issue by kodisu** [TurningPointChatbot/counseling-training-chatbot#28]
Seems that when testing a component with imports of .env variables won't allow

For example `frontend>_tests_>ModuleRow.test.ts` works.
However creating a test for the Login or Profile components do not work and this error is given: 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/55217553/183674343-cca02c52-837e-4033-b25b-813832d9e054.png">

Adding complierOptions to the `tsconfig.json` helps with the type 'ImportMeta' errors, but thats as far as I was able to debug this problem.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/55217553/183676156-ceb4cd3c-886a-42da-9c82-d30238120967.png">

Heres some links I found on the issue, but don't fully understand :(
https://bytemeta.vip/index.php/repo/kulshekhar/ts-jest/issues/3424 (Experimental mode did not work for me)
https://vitejs.dev/guide/env-and-mode.html
https://stackoverflow.com/questions/66039933/typescript-types-for-import-meta-env
https://stackoverflow.com/questions/68317339/testing-svelte-components-with-import-meta-env (we could try move to Vitetest, but not if thats better or if others already started doing testing)

**Comment by Irate-Walrus** [comment]
The auth-helpers warning should be fixed by an npm install.

**Comment by linton2000** [comment]
Looks like this is fixed so I'll close the issue.
