### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by katherinemof** [TurningPointChatbot/counseling-training-chatbot#41]
The nav bar and side bar and not working properly
Need to make sure the side navbar is correct and working on everypage (refer to figma)
Need to ensure the header navbar links are working

**Comment by linton2000** [comment]
The bug was with the Navigation routes relying on a Supabase client query. I commented out that code and hardcoded some nav values for now and got most of the navigation working in origin/fix/navigation. There are still some links to fix, especially in the admin subsystem.

**Comment by anna-giang** [comment]
This is to do with migrating to new way to access database (new API)

**Comment by anna-giang** [comment]
Sigma

**Comment by linton2000** [comment]
Links in rc4.0 should work with placeholder values now. Close this issue when the backend migration is done.

**Comment by ghost** [comment]
fixed in sigma issues
