### ISSUE TITLE
Undefined Account management values

### ISSUE THREAD

**Issue by linton2000** [TurningPointChatbot/counseling-training-chatbot#43]
After logging in, the account has undefined values for Position and Email. It doesn't display details such as full name, mobile, email and phone no. either in the fields that it renders. Maybe some API code needs to be added and Supabase client stuff updated in order to get this working again?

**Comment by anna-giang** [comment]
Sigma

**Comment by anna-giang** [comment]
This is to do with migrating to new way to access database (new API)

**Comment by Frigidity** [comment]
Fixed for email, name, profile pic and hard coded for position, should not be an issue since positions can't be edited atm. At some point someone deleted mobile from the database so have removed this from the profile
