### ISSUE TITLE
Display picture in the navbar is not the logged in user's display picture

### ISSUE THREAD

**Issue by anna-giang** [TurningPointChatbot/counseling-training-chatbot#52]
It is currently just a randomly generated photo. Need to link this up to the database.

![image](https://user-images.githubusercontent.com/49330921/190538951-5644daa2-ebf5-4dff-87f5-b570050ed041.png)

**Comment by anna-giang** [comment]
Sigma

**Comment by anna-giang** [comment]
Related to account management fetching data from database

**Comment by kodisu** [comment]
I've hardcoded the id here because I'm not sure how to check for the user id during a session login. 
However this should be working https://github.com/TurningPointChatbot/counseling-training-chatbot/commit/9cd788f386dca09e6f090ade4b3f8419a2e0b694

**Comment by Frigidity** [comment]
Fixed issue in sigma issues branch
